const livraria = {
    results: [
        {
            capa: "./img/capas/breveResp.png",
            titulo: "Breves Respostas para Grandes Questões",
            descricao: "Breves Respostas para Grandes Questões",
            editora: "Intrínseca",
            autor: "Stephen Hawking",
            edicao: 1,
            pag: 256,
            idioma: "Português",
            categoria: "Autobiografia",
            preco: 29.90,
            precoR: "medio"
        },
        {
            capa: "./img/capas/noiteMortos.png",
            titulo: "Noite dos Mortos-Vivos",
            descricao: "Noite dos Mortos-Vivos",
            editora: "Darkside",
            autor: "John Russo",
            edicao: 1,
            pag: 256,
            idioma: "Português",
            categoria: "Terror",
            preco: 76.90,
            precoR: "mais caro"
        },
        {
            capa: "./img/capas/rainhaVermelha.png",
            titulo: "A Rainha Vermelha",
            descricao: "A Rainha Vermelha",
            editora: "Seguinte",
            autor: "Victoria Aveyard",
            edicao: 1,
            pag: 448,
            idioma: "Português",
            categoria: "Fantasia",
            preco: 45.90,
            precoR: "caro"
        },
        {
            capa: "./img/capas/noMundoDaLuna.png",
            titulo: "No Mundo da Luna",
            descricao: "No Mundo da Luna",
            editora: "Verus",
            autor: "Carina Rissi",
            edicao: "Edição Ampliada",
            pag: 504,
            idioma: "Português",
            categoria: "Romance",
            preco: 26.90,
            precoR: "medio"
        },
        {
            capa: "./img/capas/criaturasEstranhas.png",
            titulo: "O Mundo de Lore: Criaturas Estranhas",
            descricao: "O Mundo de Lore: Criaturas Estranhas",
            editora: "Darkside",
            autor: "Aaron Mahnke",
            edicao: 1,
            pag: 256,
            idioma: "Português",
            categoria: "Contos",
            preco: 47.91,
            precoR: "caro"
        },
        {
            capa: "./img/capas/dracula.png",
            titulo: "Drácula (Dark Edition)",
            descricao: "Drácula (Dark Edition)",
            editora: "Darkside",
            autor: "Bram Stoker",
            edicao: "Edição Limitada",
            pag: 580,
            idioma: "Português",
            categoria: "Terror",
            preco: 59.40,
            precoR: "caro"
        },
        {
            capa: "./img/capas/medoClassico.png",
            titulo: "H.P. Lovecraft - Medo Clássico - Vol 01",
            descricao: "H.P. Lovecraft - Medo Clássico - Vol 01",
            editora: "Darkside",
            autor: "H.P. Lovecraft",
            edicao: "Edição Especial",
            pag: 384,
            idioma: "Português",
            categoria: "Terror",
            preco: 41.89,
            precoR: "caro"
        },
        {
            capa: "./img/capas/aliceMaravilha.png",
            titulo: "Alice no País das Maravilhas",
            descricao: "Alice no País das Maravilhas",
            editora: "Darkside",
            autor: "Lewis Carrol",
            edicao: 1,
            pag: 224,
            idioma: "Português",
            categoria: "Fantasia",
            preco: 54.90,
            precoR: "caro"
        },
        {
            capa: "./img/capas/pequena.png",
            titulo: "A Pequena Sereia e o Reino das Ilusões",
            descricao: "A Pequena Sereia e o Reino das Ilusões",
            editora: "Darkside",
            autor: "Louise Neill",
            edicao: 1,
            pag: 224,
            idioma: "Português",
            categoria: "Fantasia",
            preco: 54.90,
            precoR: "caro"
        },
        {
            capa: "./img/capas/colecionador.png",
            titulo: "O Colecionador",
            descricao: "O COLECIONADOR",
            editora: "Darkside",
            autor: "John Fowles",
            edicao: 1,
            pag: 256,
            idioma: "Português",
            categoria: "Terror",
            preco: 36.99,
            precoR: "medio"
        },
        {
            capa: "./img/capas/desejos.png",
            titulo: "O Colecionador de Desejos - Uma fascinante história de amor",
            descricao: "O Colecionador de Desejos - Uma fascinante história de amor",
            editora: "Universo dos Livros",
            autor: "Mia Sheridan",
            edicao: 1,
            pag: 448,
            idioma: "Português",
            categoria: "Romance",
            preco: 41.17,
            precoR: "caro"
        },
        {
            capa: "./img/capas/imperfeicoes.png",
            titulo: "Todas as suas (Im)Perfeições",
            descricao: "Todas as suas (Im)Perfeições",
            editora: "Galera",
            autor: "Collen Hoover",
            edicao: 2,
            pag: 304,
            idioma: "Português",
            categoria: "Ficção",
            preco: 26.89,
            precoR: "medio"
        },
        {
            capa: "./img/capas/assim.png",
            titulo: "É Assim que Acaba",
            descricao: "É Assim que Acaba",
            editora: "Galera",
            autor: "Collen Hoover",
            edicao: 9,
            pag: 368,
            idioma: "Português",
            categoria: "Ficção",
            preco: 39.92,
            precoR: "medio"
        },
        {
            capa: "./img/capas/caminhoLiberdade.png",
            titulo: "Um Caminho para a Liberdade",
            descricao: "Um Caminho para a Liberdade",
            editora: "Intrínseca",
            autor: "Jojo Moyes",
            edicao: 1,
            pag: 368,
            idioma: "Português",
            categoria: "Ficção",
            preco: 29.78,
            precoR: "medio"
        },
        {
            capa: "./img/capas/amorEncomenda.png",
            titulo: "Amor Sob Encomenda",
            descricao: "Amor Sob Encomenda",
            editora: "Verus",
            autor: "Carina Rissi",
            edicao: 1,
            pag: 546,
            idioma: "Português",
            categoria: "Romance",
            preco: 29.79,
            precoR: "medio"
        },
        {
            capa: "./img/capas/mentiraPerfeita.png",
            titulo: "Mentira Perfeita",
            descricao: "Mentira Perfeita",
            editora: "Verus",
            autor: "Carina Rissi",
            edicao: 1,
            pag: 462,
            idioma: "Português",
            categoria: "Romance",
            preco: 34.93,
            precoR: "medio"
        },
        {
            capa: "./img/capas/marido.png",
            titulo: "Procura-se um Marido",
            descricao: "Procura-se um Marido",
            editora: "Verus",
            autor: "Carina Rissi",
            edicao: 1,
            pag: 476,
            idioma: "Português",
            categoria: "Romance",
            preco: 26.89,
            precoR: "medio"
        },
        {
            capa: "./img/capas/entreCulpa.png",
            titulo: "Entre a Culpa e o Desejo",
            descricao: "Entre a Culpa e o Desejo",
            editora: "Gutenberg",
            autor: "Sarah MacLean",
            edicao: 1,
            pag: 304,
            idioma: "Português",
            categoria: "Romance",
            preco: 33.68,
            precoR: "medio"
        }
    ]
}

